### ISSUE TITLE
Improve tidy3d plugin

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gplugins#242]
- [x] #244
- [x] easily exploit symmetries
- [x] #243

@yaugenst

**Comment by yaugenst** [comment]
symmetries will need an extra argument here: https://github.com/gdsfactory/gplugins/blob/1464ae0523b1b8b8088ccfe77890ebb7020c04c0/gplugins/tidy3d/component.py#L179

the other two points are already supported i believe, since tidy3d supports it

should we merge first before making a tracking issue for a plugin that technically doesnt exist yet? i also have a few points for possible improvements
